main: com.winthier.decorator.DecoratorPlugin

name: Decorator
description: Populate world chunks by teleporting players around.
version: 0.1
api-version: 1.19

author: StarTux
website: https://github.com/StarTux/Decorator

depend: [Dirty]
softdepend: [Worlds]

commands:
  decorator:
    aliases: [ dec ]
    description: Decorator
    usage: |-
      /dec init <WORLD> (all)
      /dec reload
      /dec pause
      /dec save
      /dec cancel
      /dec info
      /dec fake
      /dec players
    permission: decorator.decorator

permissions:
  decorator.decorator:
    description: Use the "/decorator" command.
    default: op
