main: com.winthier.decorator.DecoratorPlugin

name: Decorator
description: Populate world chunks by teleporting players around.
version: 0.1
api-version: '1.21'

author: StarTux
website: https://github.com/StarTux/Decorator

depend: []
softdepend: [Worlds]

commands:
  decorator:
    aliases: [ dec ]
    description: Decorator
    usage: |-
      /dec init <WORLD> (all)
      /dec reload - Reload config
      /dec pause - Pause generation
      /dec save - Save todo and world
      /dec cancel - Cancel generation
      /dec info - Print generator info
      /dec fake - Spawn fake player
      /dec players - Print player info
      /dec shutdown - Schedule shutdown
    permission: decorator.decorator

permissions:
  decorator.decorator:
    description: Use the "/decorator" command.
    default: op
