name: Decorator
description: Populate world chunks by teleporting players around.
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.winthier.decorator.DecoratorPlugin
depend: [ ]
commands:
  decorator:
    aliases: [ dec ]
    description: Decorator
    usage: |-
      /dec init (all)
      /dec reload
      /dec pause
      /dec save
      /dec cancel
      /dec info
      /dec fake
      /dec players
    permission: decorator.decorator
permissions:
  decorator.decorator:
    description: Use the "/decorator" command.
    default: op
